Inverse Monte Carlo (CUDAMCML使用) の自動化

【注意事項】

ランタイムを「GPU」にすること！

ここでのコードは最小限にして、CUDAを回す部分とかは別のファイル（.py形式）にモジュールとしてまとめてあります

最終的な結果（図, csv）はlog_pathで指定したディレクトリにできます

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!nvidia-smi

Thu May 18 14:42:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
pip install natsort

Note: you may need to restart the kernel to use updated packages.


In [2]:
# pip install timeout_decorator

  Created wheel for timeout-decorator: filename=timeout_decorator-0.5.0-py3-none-any.whl size=5033 sha256=52ebb4a1d00a37b9c30517e225683e5674c81e3448e5b53883e1e20ccdd328ad
  Stored in directory: c:\users\imani\appdata\local\pip\cache\wheels\7d\64\ac\de1dd54f9a6e48b846e9cb5e4176d6f063380e7f83d69807ad
Successfully built timeout-decorator
Note: you may need to restart the kernel to use updated packages.


In [13]:
import os
import re
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import openpyxl as px
from openpyxl.styles.fonts import Font
import itertools
import time
import datetime
import subprocess
#import slackweb
from natsort import natsorted
# from timeout_decorator import timeout, TimeoutError

In [7]:
#Rd, Ttデータ読み込み

date=230523
num_spectra = 1                           #Inputファイルに含まれるスペクトル数
data_file = '/Users/imani/Desktop/optical_property/integration-sphere/main/Rd_Tt/Rd_Tt_IMC_input.csv'

measurement_data = np.loadtxt(data_file, delimiter=',', skiprows=1, usecols=[0,1,2], encoding="shift-jis")
num_measured_data = measurement_data.shape[0]

print('測定データの個数 :', num_measured_data)
print(measurement_data)


測定データの個数 : 2001
[[4.00047e+02 1.04060e-01 1.05550e-01]
 [4.00506e+02 1.02530e-01 1.06670e-01]
 [4.00964e+02 9.91800e-02 1.05460e-01]
 ...
 [6.98738e+02 2.97270e-01 4.06230e-01]
 [6.99179e+02 2.98290e-01 4.06870e-01]
 [6.99619e+02 2.98170e-01 4.07980e-01]]


In [8]:
#パス、ファイル関係の指定（絶対パス）

#CUDAMCML関係のファイル（safeprimes_base32.txtなど）があるディレクトリ
CUDA_path = '/Users/imani/Desktop/optical_property/integration-sphere/main/CUDAMCML'          

#モジュール（IMC_MakeInputfile.pyなど）があるディレクトリ
module_path = '/Users/imani/Desktop/optical_property/integration-sphere/main/module'

#ランク毎のログを残したいディレクトリ
log_path = '/Users/imani/Desktop/optical_property/integration-sphere/main/result'

#光伝搬計算に関する条件を指定したファイル
Parameter_File = '/Users/imani/Desktop/optical_property/integration-sphere/main/IMC_parameters.xlsx'


In [9]:
#ランクの設定
finish_rank  = 12                                                 #12以下で指定。ここでのrankにたどり着く前に収束したら勿論終了する

#CUDAMCMLのタイムアウト[秒]
timeout_sec = 150                                                 #よく回らんことが往々にしてある。回らん時はタイムアウトの秒数経過した時点で中断させる

#ファイル名の設定
date = 'True'                                                     #作成するファイルに日付をつけますか？（True or Falseで入力）

#slack関係
Slack_Nortification = 'False'                                      #完了したらslackに通知を送りますか？（True or Falseで入力）
Slack_url = 'https://hooks.slack.com/services/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'     #Trueのとき
'''
URLは個人で別。SlackのIncoming Webhookで各自のURLを取得してください（このURLのままだと高井のDMに完了通知が来てしまいます）
''' 

'\nURLは個人で別。SlackのIncoming Webhookで各自のURLを取得してください（このURLのままだと高井のDMに完了通知が来てしまいます）\n'

In [10]:
#ファイル確認

print('全部Trueであることを確認↓')

#モジュール
module = ['__init__.py', 'exeCUDAMCML.py', 'IMC_MakeInputfile.py', 'IMC_MoveRank.py', 'IMC_OutputResult.py']
for file in module:
    print(os.path.isfile('{:}/{:}'.format(module_path, file)))

#CUDA関係
CUDA_files = ['src', 'copying.txt', 'makefile', 'safeprimes_base32.txt']
for file in CUDA_files:
    print(os.path.exists('{:}/{:}'.format(CUDA_path, file)))


全部Trueであることを確認↓
True
True
True
True
True
True
True
True
True


################################

################################

################################

メイン

In [17]:
rank = 1

#ディレクト移動
os.chdir(CUDA_path) 

start_time = time.time()

with open('{:}/__init__.py'.format(module_path), 'r', encoding='utf-8') as f:
    script_1 = f.read()
    exec(script_1)

print('サンプル  : n', n_layer_2, 'g', g_layer_2, 'd', d_layer_2)
print('---------------------------------')


#rank 1 (.xlsxから値取得)
min_mua           = float(sheet.cell(22, 2).value)
min_mus           = float(sheet.cell(23, 2).value)
max_mua           = float(sheet.cell(22, 3).value)
max_mus           = float(sheet.cell(23, 3).value)
grid_interval_mua = float(sheet.cell(22, 4).value)
grid_interval_mus = float(sheet.cell(23, 4).value)

#rank 1 (mua, musのペア作成)
initial_mua = np.linspace(min_mua, max_mua, num = int(((max_mua-min_mua)/grid_interval_mua)+1))
initial_mus = np.linspace(min_mus, max_mus, num = int(((max_mus-min_mus)/grid_interval_mus)+1))
MC_pair   = np.array(list(itertools.product(initial_mua, initial_mus)))


while True:                                      #全部のデータが0.5%に収まらない限りは

    #そのときのrankのフォルダ作成
    if os.path.isdir('{:}/rank{:}'.format(log_path, rank)) == False:
        os.mkdir('{:}/rank{:}'.format(log_path, rank))    
        print('rank{:} // Folder created'.format(rank))
    else:
        pass

    num_MC_data = MC_pair.shape[0] 
    print('rank{:} // CUDAMCML input データ数 : {:}'.format(rank, num_MC_data))

    #input作成
    with open('{:}/IMC_MakeInputfile.py'.format(module_path), 'r', encoding='utf-8') as g:                  #IMC_MakeInputfile.pyにまとめてあります
        script_2 = g.read()
        exec(script_2)
    
    #CUDAMCML回す
    with open('{:}/exeCUDAMCML.py'.format(module_path), 'r', encoding='utf-8') as h:                        #CUDAMCML.pyにまとめてあります
        script_3 = h.read()
        exec(script_3)

    #Rd, Ttのresult取得
    result_files = glob.glob('{:}/rank{:}/CUDA_result_*.txt'.format(log_path, rank))
    result_files = natsorted(result_files)

    for read_file in result_files:
        if result_files.index(read_file) == 0:
            tmp_simulated_data = np.loadtxt(read_file, delimiter='\t')
        else:
            tmp_data = np.loadtxt(read_file, delimiter='\t')
            tmp_simulated_data = np.concatenate([tmp_simulated_data, tmp_data])

    #以前のランクのMCデータも含めて探索する（局所解から回避できるように）
    if rank == 1:
        simulated_data = tmp_simulated_data
    else:
        simulated_data = np.concatenate([simulated_data, tmp_simulated_data])
        

    print('rank{:} // CUDAMCML result データ数 : {:}'.format(rank, len(tmp_simulated_data)))
    print('rank{:} // Total データ数 : {:}'.format(rank, len(simulated_data)))

    #最適なmua, mus選定、次ランクへ
    with open('{:}/IMC_MoveRank.py'.format(module_path), 'r', encoding='utf-8') as i:                           #IMC_MoveRank.pyにまとめてあります
        script_4 = i.read()
        exec(script_4)

    MOVERANK  = MoveRank()    
    VALUES    = MOVERANK.Get_Possible_Values(measurement_data, simulated_data)
    TASK      = VALUES[0]
    RESULT    = np.array(VALUES[1])

    #ログ出力
    with open('{:}/IMC_OutputResult.py'.format(module_path), 'r', encoding='utf-8') as j:
        script_5 = j.read()
        exec(script_5)

    if TASK == 'Continue' and rank != finish_rank:          #次ランクに進む場合
        
        data_pair = np.array(VALUES[2])
        print('rank{:} // 0.5%以内のデータ数 : {:}/{:} ({:.1f}%)'.format(rank, len(RESULT)-len(data_pair), len(RESULT), (len(RESULT)-len(data_pair))/len(RESULT)*100))

        MC_pair = MOVERANK.Create_mua_mus_forMC(rank)
        print('rank{:} // rank{:}の新規mua, musペア数 : {:}'.format(rank, rank+1, len(MC_pair)))

        wavelength  = RESULT[:, 0]

        OUTPUT_RESULT = Output_result()
        OUTPUT_RESULT.Create_table()
        OUTPUT_RESULT.Create_table_next()
        OUTPUT_RESULT.Create_figures()
        print('rank{:} // ログ出力 Finished'.format(rank))
        print('rank{:} // Finished'.format(rank))
        print('---------------------------------')
        rank += 1

    else:                                                  #閾値以内に収まった場合，finish_rankに到達した場合
        if rank == finish_rank:
            data_pair = np.array(VALUES[2])
            print('rank{:} // 0.5%以内のデータ数 : {:}/{:} ({:.1f}%)'.format(rank, len(RESULT)-len(data_pair), len(RESULT), (len(RESULT)-len(data_pair))/len(RESULT)*100))
        
        wavelength  = RESULT[:, 0]
        reduced_mus = RESULT[:, 4]*(1-g_layer_2)

        OUTPUT_RESULT = Output_result()
        OUTPUT_RESULT.Create_table()
        OUTPUT_RESULT.Create_figures()
        OUTPUT_RESULT.Final_spectra()
        OUTPUT_RESULT.Csv_output()
        
        #平均と標準偏差
        if num_spectra != 1:
            OUTPUT_RESULT.Average_spectra(RESULT[:, 3], 'mua')
            OUTPUT_RESULT.Average_spectra(RESULT[:, 4], 'mus')
            OUTPUT_RESULT.Average_spectra(reduced_mus, 'reduced_mus')

        print('rank{:} // ログ出力 Finished'.format(rank))
        print('rank{:} // Finished'.format(rank))
        print('---------------------------------')
        print('ALL completed !!!')
        break                                             #ループから抜ける

os.rename('{:}/rank{:}'.format(log_path, rank), '{:}/rank{:}_finished'.format(log_path, rank))

#計算時間
calculation_time = datetime.timedelta(seconds = round(time.time() - start_time, 1))

def get_time(td):
    m, s = divmod(td.seconds, 60)
    h, m = divmod(m, 60)
    return h, m, s
h_m_s = get_time(calculation_time)

print('合計', '{:02d}:{:02d}:{:02d}'.format(h_m_s[0], h_m_s[1], h_m_s[2]), 'かかりました')

#slack通知
# if Slack_Nortification == 'False':
#     slack = slackweb.Slack(url=Slack_url)
#     slack.notify(text='IMCの計算終わりました!!!!')


サンプル  : n 1.4 g 0.97 d 1.2
---------------------------------
rank1 // CUDAMCML input データ数 : 231
rank1 // Inputfile created


'make' �́A�����R�}���h�܂��͊O���R�}���h�A
����”\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
'make' �́A�����R�}���h�܂��͊O���R�}���h�A
����”\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B


OSError: [WinError 193] %1 は有効な Win32 アプリケーションではありません。

In [ ]:
! nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


In [ ]:
!make

/usr/local/cuda-11.8/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_87,code=sm_87 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_89,code=compute_89 ./src/CUDAMCMLmain.cu -o CUDAMCML
